Hw#1 Viktoriia bortnikova
Masakinka/Python-Enchantress pull request #1
Opened 2020-12-27 18:17 UTC by Masakinka

@dimigor

2020-12-27 18:19 UTC, Masakinka commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#1-OOP-Borthikova Viktoriia](https://trello.com/c/CobK1m3J/14-hw1-oop-borthikova-viktoriia)

2020-12-29 13:45 UTC, dimigor requested changes

2020-12-29 13:45 UTC, dimigor commented on venv/animals.py
> +class Animals:
назва класу в однині

2020-12-29 13:45 UTC, dimigor commented on venv/guitare.py
> +
забагато пустих рядків вкінці

2020-12-29 13:58 UTC, Masakinka commented on venv/animals.py
> +class Animals:
Чи вірно я зрозуміла: виправити всі назви класів в однині?
Наче виправила.

2020-12-29 13:59 UTC, Masakinka commented on venv/guitare.py
> +
Видалила зайві рядки:)

2021-01-09 08:34 UTC, hallrizon-io approved these changes

2021-01-09 08:37 UTC, hallrizon-io commented on venv/laptop.py
> +        return "%s made by %s" % (self.model, self.maker) + " with diagonal " + str(self.diagonal.get_diagonal())
Нажаль таке форматування строки в пайтоні виконується довго і воно не оптимізоване.
Можна було написати трішки інакше - f"{self.model} made by {self.maker} with diagonal {self.diagonal.get_diagonal()}"

Це називається форматування f-string.
https://realpython.com/python-f-strings/

2021-01-10 12:55 UTC, Masakinka commented on venv/laptop.py
> +        return "%s made by %s" % (self.model, self.maker) + " with diagonal " + str(self.diagonal.get_diagonal())
Дякую за рекомендацію!
Буду знати:)

2021-01-10 14:24 UTC, merged