HW#2-Viktoriia-Bortnikova
Masakinka/Python-Enchantress pull request #2
Opened 2021-01-13 00:03 UTC by Masakinka

@dimigor

2021-01-13 00:04 UTC, Masakinka commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#2 - OOP_Practice - Bortnikova Viktoriia](https://trello.com/c/9t0Xl5V0/43-hw2-ooppractice-bortnikova-viktoriia)

2021-01-13 00:04 UTC, Masakinka commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#2 - OOP_Practice - Bortnikova Viktoriia](https://trello.com/c/9t0Xl5V0/43-hw2-ooppractice-bortnikova-viktoriia)

2021-01-13 00:04 UTC, Masakinka commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#2 - OOP_Practice - Bortnikova Viktoriia](https://trello.com/c/9t0Xl5V0/43-hw2-ooppractice-bortnikova-viktoriia)

2021-01-13 00:04 UTC, Masakinka commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#2 - OOP_Practice - Bortnikova Viktoriia](https://trello.com/c/9t0Xl5V0/43-hw2-ooppractice-bortnikova-viktoriia)

2021-01-13 20:13 UTC, dimigor requested changes

2021-01-13 20:13 UTC, dimigor commented on HW#2/Person.py
> +        person.make_purchase()
не забувай про endline

2021-01-13 20:13 UTC, dimigor commented on venv/HW#2/Person.py
> +This is a class Person.
це модуль)

2021-01-13 20:13 UTC, dimigor commented on venv/HW#2/Person.py
> +
так само як модуль, продокументуй клас

2021-01-17 10:29 UTC, Masakinka commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#2 - OOP_Practice - Bortnikova Viktoriia](https://trello.com/c/9t0Xl5V0/43-hw2-ooppractice-bortnikova-viktoriia)

2021-01-19 14:20 UTC, dimigor approved these changes

2021-02-03 15:33 UTC, merged