Hw#4 viktoriia bortnikova
Masakinka/Python-Enchantress pull request #4
Opened 2021-01-17 20:59 UTC by Masakinka

@dimigor

2021-01-17 21:02 UTC, Masakinka commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#4 - Tests - Viktoriia Bortnikova](https://trello.com/c/0MgefcTJ/74-hw4-tests-viktoriia-bortnikova)

2021-01-19 15:39 UTC, dimigor requested changes

2021-01-19 15:39 UTC, dimigor commented on HW#4/test_hen_class.py
> +
Зроби також кілька хибних тест кейсів

2021-01-19 15:39 UTC, dimigor commented on tests/hen_house/hen_class.py
> +                 }
зроби цей хардкод оптмальнішим)

2021-01-19 15:39 UTC, dimigor commented on tests/hen_house/hen_class.py
> +
багато рядків порожніх
слідкуй за форматуванням

2021-01-27 11:26 UTC, dimigor approved these changes

2021-02-03 15:33 UTC, merged